### ISSUE TITLE
Players joining causes "Could not pass event PlayerJoinEvent to iDisguiseAdditions"

### ISSUE THREAD

**Issue by Formula350** [robingrether/iDisguiseAdditions#1]
Running Spigot 1.11.2
iDisguise v5.6.4 *([config](https://gist.github.com/Formula350/b7a21519566458fdb84021e71f0227fd) file)*
iDisguise Additions v1.4 *([config](https://gist.github.com/Formula350/37b0aff72d975fad821124c804a5af9d) file)*
(and some 90 others whose relevance I can't begin to speculate on).

Any time a player joins, any player, and all players (myself included), is met with the errors below. They're the same, but I simply provided three of them to illustrate that it happens no matter what. 

Realistically, the only feature being used is this ignore-disguised-players option, as only Ops will have access to the Disguise as Player ability in the main plugin; thus, the Use Player Name option wouldn't be applicable to these players joining. Even then, most of the players lack **any** disguise permissions.

If any further details or testing is needed, please let me know.
Thanks,
-Formula350

````java
[04:01:46] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to iDisguiseAdditions v1.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at de.robingrether.idisguise.iDisguise$7.getDisguise(iDisguise.java:884) ~[?:?]
	at de.robingrether.idisguise.additions.EventListenerLegacy.onPlayerJoin(EventListenerLegacy.java:106) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	... 14 more
[04:01:46] [Server thread/INFO]: Emilicious logged in with entity id 4243 at ([CHB-Redux]-157.0217503726466, 76.0, 1313.901464325484)
````
````java
[04:01:47] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to iDisguiseAdditions v1.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at de.robingrether.idisguise.iDisguise$7.getDisguise(iDisguise.java:884) ~[?:?]
	at de.robingrether.idisguise.additions.EventListenerLegacy.onPlayerJoin(EventListenerLegacy.java:106) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	... 14 more
[04:01:47] [Server thread/INFO]: ColdCreeperMC logged in with entity id 4435 at ([world_nether]131974.6817853245, 128.23625203141623, 132352.63017720747)
````
````java
[04:02:51] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to iDisguiseAdditions v1.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at de.robingrether.idisguise.iDisguise$7.getDisguise(iDisguise.java:884) ~[?:?]
	at de.robingrether.idisguise.additions.EventListenerLegacy.onPlayerJoin(EventListenerLegacy.java:106) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-twkd.jar:git-Spigot-3fb9445-2b6c9f4]
	... 14 more
[04:02:51] [Server thread/INFO]: sam72909 logged in with entity id 5278 at ([world_the_end]-530.5, 59.0, 367.50518560490855)
````

**Comment by luisagrether** [comment]
I have already fixed this error. Just go and download iDisguise 5.6.5-SNAPSHOT #1 from over here: https://www.robingrether.de/idisguise/

**Comment by Formula350** [comment]
Doh... My apologies!
That indeed solved it, thank you!
